// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Subscription.Data;

namespace Subscription.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221113091720_SubscriptionName")]
    partial class SubscriptionName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Subscription.Models.SubscriptionName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Is_Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Subscription_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Is_Enabled = true,
                            Subscription_Name = "invoice-smash-master-test@coupadev.com"
                        },
                        new
                        {
                            Id = 2L,
                            Is_Enabled = true,
                            Subscription_Name = "invoice-smash-dashmaster3@coupadev.com"
                        },
                        new
                        {
                            Id = 3L,
                            Is_Enabled = true,
                            Subscription_Name = "invoice-smash-master@coupadev.com"
                        },
                        new
                        {
                            Id = 4L,
                            Is_Enabled = true,
                            Subscription_Name = "invoice-smash-mlgateKeeper@coupadev.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
